[project]
name = "velqimobile"
version = "1.0.0"
description = "Velqi Mobile - Music search and player"
requires-python = ">=3.8"
dependencies = [
    "flet>=0.25.0",
    "yt-dlp>=2024.11.11",
]

[tool.flet]
project = "velqimobile"
description = "Velqi Mobile - Music search and player"
product = "Velqi Mobile"

[tool.flet.android]
split-per-abi = true
cleanup-app = true
cleanup-packages = true
compile-app = true
compile-packages = true
exclude = ["*.pyc", "__pycache__", "*.log", "tests/*", "venv/*"]
