[project]
name = "velqilite"
version = "1.0.0"
description = "Velqi Lite - Music downloader"
requires-python = ">=3.8"
dependencies = [
    "flet==0.85.1",
    "yt-dlp==2024.11.11",
    "requests==2.31.0",
]

[tool.flet]
project = "velqilite"
description = "Velqi Lite Music Downloader"
product = "Velqi Lite"

[tool.flet.android]
split-per-abi = true
cleanup-app = true
cleanup-packages = true
compile-app = true
compile-packages = true
